exec-once = uwsm app -- hypridle
exec-once = uwsm app -- mako
exec-once = uwsm app -- fcitx5
exec-once = uwsm app -- ln -sf /usr/share/backgrounds/bluefin/$(date +%m)-bluefin-night.jxl ~/.config/omadora/current/background && swaybg -i ~/.config/omadora/current/background -m fill
#exec-once = uwsm app -- swayosd-server
exec-once = systemctl --user enable --now hyprpolkitagent.service
exec-once = sleep 2 && $HOME/.local/share/omadora/install/config/detect-keyboard-layout.sh
